#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Mar 06 15:52:38 CET 2024
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_and_module_behav -key {Behavioral:sim_1:Functional:tb_and_module} -tclbatch tb_and_module.tcl -view /home/lsriw/Desktop/jakub_grabowski/lab2/tb_and_module_behav.wcfg -log simulate.log"
xsim tb_and_module_behav -key {Behavioral:sim_1:Functional:tb_and_module} -tclbatch tb_and_module.tcl -view /home/lsriw/Desktop/jakub_grabowski/lab2/tb_and_module_behav.wcfg -log simulate.log

